name: example
description: An example for derry.

environment:
  sdk: ">=2.8.1 <3.0.0"

dev_dependencies:
  derry:
    path: ../

scripts:
  version: dart --version
  ping: ping google.com
  test:
    - echo test
    - echo done
