name: derry
description: A script manager for dart.
version: 0.0.1
homepage: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.8.1 <3.0.0"

executables:
  derry:

dependencies:
  ffi: ^0.1.3
  args: ^1.6.0
  yaml: ^2.2.1
  console: ^3.1.0
  equatable: ^1.2.0

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0
