name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.2.1
repository: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.10.0 <3.0.0"

executables:
  derry:

dependencies:
  args: ^1.6.0
  console: ^3.1.0
  equatable: ^1.2.0
  ffi: ^0.1.3
  path: ^1.7.0
  string_similarity: ^1.0.1
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.0
  build_version: ^2.0.1
  import_sorter: ^4.3.0
  lint: ^1.3.0
  test: ^1.6.0

scripts: derry.yaml

import_sorter:
  comments: false
