name: derry
description: Derry is a script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.1.0
homepage: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.8.1 <3.0.0"

executables:
  derry:

dependencies:
  ffi: ^0.1.3
  args: ^1.6.0
  yaml: ^2.2.1
  console: ^3.1.0
  equatable: ^1.2.0
  string_similarity: ^1.0.1

dev_dependencies:
  test: ^1.6.0
  lint: ^1.3.0
  build_runner: ^1.10.0
  build_version: ^2.0.1
  import_sorter: ^4.3.0

scripts: derry.yaml
