[package]
name = "executor"
version = "0.1.0"
authors = ["frencojobs <frenco.willian@gmail.com>"]
edition = "2018"

[lib]
name = "executor"
crate-type = ["cdylib"] # dynamic library

[dependencies]
ctrlc = "3.1.4"
shared_child = "0.3.4"
colored = "2"